# Generated by Django 6.0.1 on 2026-04-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_student_avatar_student_gender"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("student", "opportunity"), name="uq_report_student_opportunity"
            ),
        ),
    ]
