# Generated by Django 6.0.5 on 2026-05-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_fetch_session'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaderboardentry',
            name='uq_leaderboard_rank',
        ),
    ]
