from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views, admin_views

urlpatterns = [
    path("", views.hello, name="home"),
    path("about-us/", views.about_us, name="about_us"),
    path("contact-us/", views.contact_us, name="contact_us"),
    path("register/", views.register_view, name="register"),
    path("terms-of-service/", views.terms_of_service, name="terms_of_service"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("opportunities/", views.opportunities, name="opportunities"),
    path("leaderboard/", views.leaderboard, name="leaderboard"),
    path("bookmarks/", views.bookmarks, name="bookmarks"),
    path("bookmarks/toggle/<int:opp_id>/", views.toggle_bookmark, name="toggle_bookmark"),
    path("profile/", views.profile, name="profile"),
     path("logout/", LogoutView.as_view(next_page="home"), name="logout"),
     path("dashboard/", views.dashboard, name="dashboard"),
     path("faq/", views.faq, name="faq"),
     path("profile/delete/", views.delete_account, name="delete_account"),
     path("opportunities/submit/",               views.submit_opportunity,    name="submit_opportunity"),
     path("opportunities/submit/success/",       views.submission_success,    name="submission_success"),
     path("opportunities/<int:opp_id>/detail/", views.opp_detail,         name="opp_detail"),
     path("opportunities/<int:opp_id>/report/", views.report_opportunity,  name="report_opportunity"),
     path("opportunities/<int:opp_id>/rate/",   views.rate_opportunity,    name="rate_opportunity"),

    # Admin panel
    path("admin-panel/login/",      admin_views.admin_login,       name="admin_login"),
    path("admin-panel/logout/",     admin_views.admin_logout,      name="admin_logout"),
    path("admin-panel/",            admin_views.admin_dashboard,   name="admin_dashboard"),
    path("admin-panel/submissions/<int:sub_id>/approve/", admin_views.admin_approve_submission, name="admin_approve_submission"),
    path("admin-panel/submissions/<int:sub_id>/reject/",  admin_views.admin_reject_submission,  name="admin_reject_submission"),
    path("admin-panel/opportunities/",         admin_views.admin_opportunities,   name="admin_opportunities"),
    path("admin-panel/opportunities/add/",     admin_views.admin_add_opportunity, name="admin_add_opportunity"),
    path("admin-panel/opportunities/<int:opp_id>/edit/",   admin_views.admin_edit_opportunity,   name="admin_edit_opportunity"),
    path("admin-panel/opportunities/<int:opp_id>/delete/", admin_views.admin_delete_opportunity, name="admin_delete_opportunity"),
    path("admin-panel/opportunities/<int:opp_id>/detail/", admin_views.admin_opp_detail_partial, name="admin_opp_detail_partial"),
    path("admin-panel/reports/",    admin_views.admin_reports,     name="admin_reports"),
    path("admin-panel/reports/<int:report_id>/resolve/", admin_views.admin_resolve_report, name="admin_resolve_report"),
    path("admin-panel/audit-log/",      admin_views.admin_audit_log,       name="admin_audit_log"),
    path("admin-panel/analytics/",      admin_views.admin_analytics,       name="admin_analytics"),
    path("admin-panel/ai-validations/", admin_views.admin_ai_validations,  name="admin_ai_validations"),
    path("admin-panel/ai-validations/monitor/",                        admin_views.admin_monitor_opportunities,   name="admin_monitor_opportunities"),
    path("admin-panel/ai-validations/monitor/progress/",               admin_views.admin_monitor_progress,        name="admin_monitor_progress"),
    path("admin-panel/ai-validations/monitor/<int:session_id>/",       admin_views.admin_monitor_session_results, name="admin_monitor_session_results"),
    path("admin-panel/ai-validations/monitor/save-schedule/",         admin_views.admin_save_monitor_schedule,   name="admin_save_monitor_schedule"),
    path("admin-panel/fetch-opportunities/", admin_views.admin_fetch_opportunities, name="admin_fetch_opportunities"),
    path("admin-panel/fetch-opportunities/run/", admin_views.admin_run_fetch, name="admin_run_fetch"),
    path("admin-panel/fetch-opportunities/save-schedule/", admin_views.admin_save_schedule, name="admin_save_schedule"),
    path("admin-panel/fetch-opportunities/session/<int:session_id>/", admin_views.admin_fetch_session_detail, name="admin_fetch_session_detail"),
    path("admin-panel/scheduler-status/", admin_views.admin_scheduler_status, name="admin_scheduler_status"),
]