# Generated by Django 5.2.14 on 2026-05-16 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_subvalidation_failed_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_at", models.DateTimeField(auto_now_add=True)),
                ("checked", models.IntegerField(default=0)),
                ("auto_closed", models.IntegerField(default=0)),
                ("errors", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-run_at"],
            },
        ),
        migrations.CreateModel(
            name="MonitorResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_decision", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitor_results",
                        to="accounts.opportunity",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="accounts.monitorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["ai_decision"],
            },
        ),
    ]
