# Generated by Django 6.0.1 on 2026-04-19 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_admin_password_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="aidiscovery",
            name="result_label",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="aidiscovery",
            name="step_log",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="FetchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("total_searches", models.IntegerField(default=0)),
                ("total_found", models.IntegerField(default=0)),
                ("total_added", models.IntegerField(default=0)),
                ("total_skipped", models.IntegerField(default=0)),
                ("total_failed", models.IntegerField(default=0)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fetch_sessions",
                        to="accounts.admin",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aidiscovery",
            name="fetch_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discoveries",
                to="accounts.fetchsession",
            ),
        ),
    ]
