# Generated by Django 5.2.14 on 2026-05-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_fetchschedule_alter_admin_id_alter_aidiscovery_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="company_domain",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
