# Generated by Django 5.2.14 on 2026-05-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_monitorsession_monitorresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly")],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("day_of_week", models.IntegerField(blank=True, null=True)),
                ("run_at_time", models.TimeField(default="09:00")),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Monitor Schedule",
            },
        ),
    ]
